DROP TABLE BOARD;

CREATE TABLE BOARD
(
	BNO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(32),
	TITLE VARCHAR2(32),
	CONTENT VARCHAR2(300),
	POSTDATE DATE,
	LASTMODIFIED DATE,
	IP VARCHAR2(100),
	HIT NUMBER,
	IMAGE VARCHAR2(300)
);

ALTER TABLE BOARD ADD FOREIGN KEY (WRITER) REFERENCES MEMBER(ID);

DROP SEQUENCE BOARD_SEQ;

CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

COMMIT