DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(32) NOT NULL UNIQUE,
	PW VARCHAR2(32) NOT NULL,
	NAME VARCHAR2(32),
	PHONE VARCHAR2(64),
	EMAIL VARCHAR2(100) NOT NULL,
	ADDRESS VARCHAR2(100),
	REGDATE DATE,
	STATE NUMBER -- 1이면 가입, 2면 탈퇴
);

DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

COMMIT

INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'admin', '1111', '관리자', '010-1111-1111', 'admin@home.com', '인터넷', SYSDATE, 1);